services:

  frontend:
    image: react-app2:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    volumes:
      # Mount custom nginx config to the same path used in the image
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    networks:
      - app_net


  backend:
    image: react-app2-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend1_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/react_app2_practice
    depends_on:
      - mongo
    networks:
      - app_net
  backend2:
    image: react-app2-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend2_container
    restart: always
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/react_app2_practice
    depends_on:
      - mongo
    networks:
      - app_net
  mongo:
    image: mongo:6
    container_name: react2_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
volumes:
  mongo_data:
