version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    restart: always

    ports:
      - "8080:8080"    # Jenkins UI
      - "50000:50000"  # Jenkins agents (important)

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - ci_net

networks:
  ci_net:
    driver: bridge

volumes:
  jenkins_home: